install.packages("reticulate")
try(reticulate::install_miniconda("miniconda"))
renv::use_python("miniconda/bin/python")
renv::restore()
writeLines("TAR_SCRIPT_ASK=false", ".Renviron")
rstudioapi::restartSession()
