install.packages(c(
  "corrr",
  "fst",
  "keras",
  "qs",
  "recipes",
  "remotes",
  "rmarkdown",
  "rprojroot",
  "rsample",
  "tidyverse",
  "usethis",
  "visNetwork",
  "yardstick"
))
remotes::install_github("rstudio/reticulate")
remotes::install_github("wlandau/targets")
remotes::install_github("wlandau/tarchetypes")
reticulate::install_miniconda()
keras::install_keras()
